### ISSUE TITLE
Feature: media player volume

### ISSUE THREAD

**Issue by metbril** [htmltiger/numberbox-card#102]
Not sure if it's possible at all but it would be nice to have support for media player entities in an entities card. Something like this

```
type: entities
entities:
  - entity: media_player.office_speaker
    type: custom:numberbox-card # <--
  - entity: number.office_speaker_bass
    type: custom:numberbox-card
```

**Comment by junkfix** [comment]
Does this work? 
```yaml
type: entities
entities:
  - type: custom:numberbox-card
    entity: media_player.office_speaker
    icon: mdi:speaker
    state: volume_level
    service: media_player.volume_set
    param: volume_level
    min: 0
    max: 1
    step: 0.1
```
