### ISSUE TITLE
Not working with input_boolean as toggle

### ISSUE THREAD

**Issue by JCPvanHooren** [htmltiger/numberbox-card#111]
Am I right that the 'toggle' function doesn't work with an input_boolean?
Could it be enabled to toggle an input_boolean instead of a switch?

I'm trying to build a sleeptimer for my bedroom A/C, hence want the 'toggle' to turn the timer on/off. Since this cannot be done directly with a timer, I'm working with an input_boolean toggle + automation.

**Comment by ildar170975** [comment]
See no issues here.
![изображение](https://github.com/junkfix/numberbox-card/assets/71872483/bd5ddc63-78bd-4fb4-9948-4f4fbab90f36)
```
type: entities
entities:
  - type: custom:numberbox-card
    entity: input_number.test_number
    name: toggle
    toggle_entity: input_boolean.test_boolean
  - input_boolean.test_boolean
title: toggle
```
