### ISSUE TITLE
Request: Cover entities

### ISSUE THREAD

**Issue by lukyjay** [htmltiger/numberbox-card#112]
Hi

Can this card be updated to support cover entities?

Thank you

**Comment by lukyjay** [comment]
@junkfix I do not know javascript but have made some tweaks through trial and error and seem to have it working now: https://github.com/lukyjay/coverbox-card/blob/main/coverbox-card.js

I couldn't get the current state part to work, so I used Gemini to help with that part but ended up cutting out most of it since it did not work.

Is this something that could be combined into your card? I had to replace some of your work since I'm not familiar with js so I can't submit a pull request (unless you think I should just add a bunch of 'if' statements with replicated code?)

**Comment by junkfix** [comment]
would something like this work? 
```yaml
type: entities
entities:
  - type: custom:numberbox-card
    entity: cover.testcover
    state: percentage
    service: cover.set_cover_position
    param: position
    min: 0
    max: 100
    step: 10
```
