### ISSUE TITLE
Card value not updating when entity updates

### ISSUE THREAD

**Issue by amosstorkey** [htmltiger/numberbox-card#114]
Unlike most other cards the numberbox does not seem to reliably update the number value on a visible dashboard when externally changed e.g. by some automation. It does seem to update on the first occasion bit subsequently doesn't.

Sadly I haven't been able to find the cause of this.

**Comment by ildar170975** [comment]
Do not confirm.
4.17
2025.2.4

1. Automation:
```
alias: test_numberbox
description: ""
triggers:
  - trigger: time_pattern
    seconds: /5
actions:
  - action: input_number.increment
    target:
      entity_id: input_number.test_number
    data: {}
mode: single
``` 
![Image](https://github.com/user-attachments/assets/5da9af36-ec8d-48d7-8e1d-9670ce87aed2)

2. Changing in another card:
![Image](https://github.com/user-attachments/assets/79b70ae7-c661-4b6c-9e59-11b654500126)

Test card:
```
type: entities
entities:
  - entity: input_number.test_number
  - type: custom:numberbox-card
    entity: input_number.test_number
```
