### ISSUE TITLE
Default unit format

### ISSUE THREAD

**Issue by dodekaphilist** [htmltiger/numberbox-card#37]
The current implementation for the unit has some issues with formatting as it's deviating from the system:

![image](https://user-images.githubusercontent.com/31287077/152873768-2dd5dcbc-36ea-493a-8432-e0c144347fbd.png)

1. The font is smaller and in the color for secondary text -> use the same format for both number and unit
2. There's no space between the number and the unit (see [here](https://physics.nist.gov/cuu/Units/checklist.html#:~:text=There%20is%20a%20space%20between%20the%20numerical%20value%20and%20unit%20symbol)) -> automatically add a space if a unit is entered

It would be nice if the card could better integrate into the system and follow its conventions. Thanks! 🙂

**Comment by htmltiger** [comment]
Some of us are not happy with the default choice but you can make the above changes using card mod

```yaml
type: entities
entities:
  - entity: input_number.my_slider
    type: 'custom:numberbox-card'
    style: |
      .cur-unit{font-size:100% !important; opacity:1 !important; padding-left:1em !important}
```
