### ISSUE TITLE
Request: Support for timer helper

### ISSUE THREAD

**Issue by fusionstream** [htmltiger/numberbox-card#43]
Support for timer helper would be nice. This way the timer duration can be adjusted directly instead of having to have another number that is editable, and then populating a timer with said number

**Comment by htmltiger** [comment]
3.9 should work
```
type: entities
entities:
  - type: custom:numberbox-card
    entity: timer.heating
    icon: mdi:fire
    service: timer.start
    param: duration
    state: duration
    min: 0
    max: 999999
    step: 60
    unit: time
```
