### ISSUE TITLE
Feature Request: Support for input date time helper

### ISSUE THREAD

**Issue by clau-bucur** [htmltiger/numberbox-card#45]
Please consider adding support for **input_datetime { has_time: true }** input helpers.
I've tried the following, it displays the state but it's not changing it from -/+:
```
input_datetime:
  irrigation_duration_manual:
    name: Irrigation manual cycle duration
    has_time: true

type: custom:numberbox-card
entity: input_datetime.irrigation_duration_manual
service: input_datetime.set_datetime
param: timestamp
state: timestamp
unit: time
```

Thank you!

**Comment by htmltiger** [comment]
Have you tried adding this?
```
min: 0
max: 999999999
step: 1
```

**Comment by htmltiger** [comment]
3.12 should work, 
```
type: entities
entities:
  - type: custom:numberbox-card
    entity: input_datetime.irrigation_duration_manual
    service: input_datetime.set_datetime
    param: time
    unit: time
    speed: 300
    step: 60
```
