### ISSUE TITLE
secondary_info not refreshing data

### ISSUE THREAD

**Issue by murcin** [htmltiger/numberbox-card#52]
when I set secondary info as some entities that automatically not refreshing
In this example I`ve use browser_mod.popup and shows variables

`            - entity: >
                [[[ return variables.s_set ]]]
              name: 'Zadana temp.:'
              type: custom:numberbox-card
              secondary info: >
                [[[ return 'zapisana: ' + states[variables.s_set].state + '°C' ]]]`
I upload screen because formatting not works perfectly...
![image](https://user-images.githubusercontent.com/66697668/183509140-5605d680-e00a-47df-88ec-bcefec4ecd03.png)

![image](https://user-images.githubusercontent.com/66697668/183508547-8d81d3ee-40d7-44b7-a87b-b63aa4f10e9f.png)
after press + or - variable one line below change with secondary_info "Teraz" - means "Now" but secondary info from numberbox-card not refreshing:

![image](https://user-images.githubusercontent.com/66697668/183508933-aaeb282e-daad-4955-8368-b0d4a766f4a4.png)

**Comment by htmltiger** [comment]
have you tried this?
secondary info: "zapisana: %variables.s_set:state °C"

**Comment by Murcin86** [comment]
yes I`ve try...

            - entity: > 
                [[[ return variables.s_set ]]] 
              name: 'Zadana temp.:' 
              type: custom:numberbox-card 
              secondary_info: > 
                [[[ return "zapisana: %variables.s_set:state °C" ]]]
here is two options: 
1) what I have right now
2) your solution - shows text - not value from entity
![image](https://user-images.githubusercontent.com/95655881/186745692-4d22828b-ea8c-4064-bb4c-d9045c55582f.png)

![image](https://user-images.githubusercontent.com/95655881/186745798-9932fc41-a381-42d3-9235-15d4f30cea6d.png)


BTW - when I using in dashboard I can use direct access to entity - thats work... but I want to use like above with custom:button-card to have something like template

      - entity: input_number.therm_julia
        type: custom:numberbox-card
        secondary_info: |
          zapisana:<b style="color:white"> %sensor.tempset_julia:state °C</b>

**Comment by htmltiger** [comment]
try ``%%`` as it may be escaping 
```[[[ return "zapisana: %%variables.s_set:state °C" ]]]```

**Comment by Murcin86** [comment]
add %% makes the same but with % sign

![image](https://user-images.githubusercontent.com/95655881/186889327-7a5a219f-8d3b-42af-90e9-ae008571c2ca.png)

**Comment by htmltiger** [comment]
instead of
```
secondary_info: > 
            [[[ return "zapisana: %variables.s_set:state °C" ]]]
```

have you tried

```
secondary_info: "zapisana: %variables.s_set:state °C"

```
as the first one is sending the variables directly to the card and do not get the updated information

**Comment by murcin** [comment]
I try it - not working :(
first entity - working - not refreshing data
second entity - not working, everything what I put wit " " or ' ' sign - does it as text...
![image](https://user-images.githubusercontent.com/66697668/187044702-fcde0a9b-945d-4be2-b277-59dad08bbc58.png)
![image](https://user-images.githubusercontent.com/66697668/187044705-89000871-3058-4d82-8f53-a224356efdb1.png)

**Comment by htmltiger** [comment]
how about if you put this way?
```
secondary_info: |
        zapisana: %variables.s_set:state °C
```

**Comment by murcin** [comment]
without % we can see text...
![image](https://user-images.githubusercontent.com/66697668/187088879-e6301800-467f-4246-aa50-447fe918f3bf.png)
![image](https://user-images.githubusercontent.com/66697668/187088885-81c5a603-18b7-463b-bc34-ef98c6911f3f.png)

with % got error with saving:
![image](https://user-images.githubusercontent.com/66697668/187088906-4506b2dc-1df0-4edf-9905-cf882b0244d3.png)
![image](https://user-images.githubusercontent.com/66697668/187088912-ae9761a8-f697-436e-ac1e-51c7bd90e7fa.png)

**Comment by ildar170975** [comment]
@murcin 
You keep using "[[[ ... ]]]" - WHY ?
And you have been proposed several times not to use it.
These "[[[ ...]]]" brackets are NOT specified in the docs (as well as "return") - then probably you should not use it.

**Comment by murcin** [comment]
you mean on line where is -entity? - because I`ve used variables from custom:button-card - and line like this doesn`t work
![image](https://user-images.githubusercontent.com/66697668/187608229-1f646b3c-d6e5-4e7c-8da7-0fb8e1a3c82a.png)
![image](https://user-images.githubusercontent.com/66697668/187608269-075ee508-a326-4da3-9258-30de4cd2e3c3.png)

and as I wrote above - when I try to use like this - shows me text:
![image](https://user-images.githubusercontent.com/66697668/187608383-390cba07-9b99-4145-9811-e7e6b91456b6.png)
![image](https://user-images.githubusercontent.com/66697668/187608431-64617e75-cb55-492a-9fdf-4344b51bddea.png)

and when I try to add % sign got error and can`t save file:
![image](https://user-images.githubusercontent.com/66697668/187608521-e77ed1a0-ed87-4728-8994-cc005922e2bb.png)
![image](https://user-images.githubusercontent.com/66697668/187608557-44309f9d-3f54-400b-b4a5-b186ba2eb55a.png)

**Comment by murcin** [comment]
here I have small example and I think that`s not problem with syntax... but your code can`t read variable state, have a look below, first example WORKS and there is 
              secondary_info: >
                that works: %input_number.therm_gabinet:state °C

second the same but should read variable state:
              secondary_info: >
                that works: %variables.s_set:state °C

![image](https://user-images.githubusercontent.com/66697668/187609543-0a871bf5-62ce-4d0b-a4a1-7375648bd28f.png)
![image](https://user-images.githubusercontent.com/66697668/187609581-453a3155-96ac-4395-abc7-9786818e9171.png)

**Comment by ildar170975** [comment]
> you mean on line where is -entity?

No, I guessed that this is a part of button-card.
And you should NOT test your issue with "secondary_info" inside ANOTHER card.
A code for testing your issue should be as simple as possible.

Two things are probably here:
1. If something is not updated inside button-card - then this is a button-card's issue, you must define entities as "monitored" - see docs for "button-card".
2. Since button-card already has a template support - then you probably should use either a "pure button-card template" or a "pure numberbox template".

First test your numberbox card OUTSIDE button-card.

**Comment by murcin** [comment]
I don`t think that custom:button-card have any problem because I set variable to custom:numberbox-card and that` work, I made small experience:

![image](https://user-images.githubusercontent.com/66697668/187662368-478283fe-b1a1-402f-8f48-75d6e1e3aa0d.png)

1 entity as variable, secondary info from input_number - WORKS
2 entity as variable, secondary info from variable - DOESN`T work
3 entity as variable no custom:numberbox-card just entity - refreshing data works

![image](https://user-images.githubusercontent.com/66697668/187663468-32bbb022-6177-411d-8f7e-a37b3fbf5707.png)


so that`s mean custom:numberbox-card can read entity from variable correctly but reading secondary info not.

**Comment by htmltiger** [comment]
It looks like variables get out of scope or not available to numberbox.

I cannot test about the variables, if your first example works with input_number then numberbox is working correctly

**Comment by ildar170975** [comment]
Consider this example:
```
type: vertical-stack
cards:
  - type: custom:button-card
    name: "[ static text ]"
    <<: &ref_settings
      variables:
        SENSOR: '[[[return entity.entity_id]]]'
      entity: input_number.test_parrots
      styles:
        grid:
          - grid-template-areas: '"i" "n" "numberbox"'
          - grid-template-columns: 1fr
          - grid-template-rows: 32px min-content min-content
    custom_fields:
      numberbox:
        card:
          type: custom:numberbox-card
          entity: input_number.test_parrots
          secondary_info: >-
            [[[ return "<b style='color:red'>" + "static" + "</b>"]]]
  - type: custom:button-card
    name: "[ variable.xxx ]"
    <<: *ref_settings
    custom_fields:
      numberbox:
        card:
          type: custom:numberbox-card
          entity: input_number.test_parrots
          secondary_info: >-
            [[[ return "<b style='color:red'>" + states[variables.SENSOR].state + "</b>"]]]
  - type: custom:button-card
    name: "%entity"
    <<: *ref_settings
    custom_fields:
      numberbox:
        card:
          type: custom:numberbox-card
          entity: input_number.test_parrots
          secondary_info: >-
            <b style='color:red'> %input_number.test_parrots:state </b>
  - type: custom:button-card
    name: "% [ variable ]"
    <<: *ref_settings
    custom_fields:
      numberbox:
        card:
          type: custom:numberbox-card
          entity: input_number.test_parrots
          secondary_info: >-
            <b style='color:red'> %[[[return variables.SENSOR]]]:state </b>
```
![image](https://user-images.githubusercontent.com/71872483/187751775-acc1ba6c-a7c0-4b8a-8524-0db0d33790de.png)

cases 1, 2 - button-card-like templates are used ("[[[ ... ]]]").
cases 3, 4 - numberbox-like templates are used ("% ... ").

Note that you may combine html-formatting from "numberbox" and  button-card-like templates (cases 1, 2).

Case 4 - does not work.
It happens probably due to an order of resolving: first numberbox-level template is resolved (and fails), then button-card-level template is resolved (which fails too).

Regarding "no refresh".
In my test, when I press "+ / -" buttons, the "secondary_info" is refreshed too - after a couple of seconds.
[Earlier I wrote about "monitored entities"](https://github.com/htmltiger/numberbox-card/issues/52#issuecomment-1232647576) - I meant a bit different situation: pressing "+ / -" affects some entity which is NOT defined as the MAIN entity for the button card, [check here](https://github.com/custom-cards/button-card#triggers_update).


As a conclusion - this is not a bug of numberbox!
