### ISSUE TITLE
unit=time: wrong data displayed

### ISSUE THREAD

**Issue by ildar170975** [htmltiger/numberbox-card#58]
Consider this example:
```
type: entities
entities:
  - entity: input_number.test_negative_1
    name: standard
  - type: custom:numberbox-card
    entity: input_number.test_negative_1
    name: unit=time (with ss)
    unit: time
  - type: custom:numberbox-card
    entity: input_number.test_negative_1
    name: unit=timehm
    unit: timehm
```

```
  test_negative_1: &ref_test_nagative_values
    min: -10000000
    max: 10000000
    step: 0.1
    mode: box
```

Output is:
![изображение](https://user-images.githubusercontent.com/71872483/187533496-f7f73e72-0c70-46e7-ac42-b0da3a2a91b6.png)

1. A value for "seconds" is wrong - it must be "4.4".
2. Imho the "seconds" value should be rounded.
