### ISSUE TITLE
entity with image: no image displayed

### ISSUE THREAD

**Issue by ildar170975** [htmltiger/numberbox-card#59]
The latest rev. 3.15 installed:
![изображение](https://user-images.githubusercontent.com/71872483/187538325-a5011cd5-d58d-4174-bcaa-9ad40394f62b.png)

Consider this example with 2 entities:

1. Entity is specified w/o `entity_picture`:
```
  test_number:
    min: 0
    max: 1000
    step: 1
    mode: slider
    icon: mdi:car
```

2. Entity with `entity_picture` specified:
```
input_number:
  test_number_with_picture:
    min: -100
    max: 100
    step: 0.1
    mode: box

homeassistant:
  customize:
    input_number.test_number_with_picture:
      entity_picture: /local/images/test/lightgreen.jpg
```

Card:
```
type: entities
entities:
  - type: section
    label: image is added
  - entity: input_number.test_number
    image: /local/images/test/orange.jpg
  - type: custom:numberbox-card
    entity: input_number.test_number
    picture: /local/images/test/orange.jpg

  - type: section
    label: number with entity_picture
  - entity: input_number.test_number_with_picture
  - type: custom:numberbox-card
    entity: input_number.test_number_with_picture
```
In both cases `numberbox-card` does not show an image:
![изображение](https://user-images.githubusercontent.com/71872483/187538896-27f66428-9bd0-475f-aa97-df8f2f3a2987.png)

If `icon: false` is added:
![изображение](https://user-images.githubusercontent.com/71872483/187539126-9e362760-5b06-421d-b2c4-c59b4d2915d4.png)

Below - my proposals how to show an icon & picture dependently on:
-- if `entity_picture` is defined;
-- values of `icon` & `picture` options.

![изображение](https://user-images.githubusercontent.com/71872483/187542430-667e11f0-eeac-49e2-bb79-010e331c4980.png)

**Comment by ildar170975** [comment]
Not working with an entity with "entity_picture":
```
type: entities
title: entity_picture
entities:
  - type: custom:numberbox-card
    entity: input_number.test_number_with_picture

  - type: custom:numberbox-card
    entity: input_number.test_number_with_picture
    icon: false

  - type: custom:numberbox-card
    entity: input_number.test_number_with_picture
    icon: mdi:car
```
![image](https://user-images.githubusercontent.com/71872483/187740932-7b78afb1-5832-4440-92fe-2d2e36053cc8.png)

![image](https://user-images.githubusercontent.com/71872483/187741017-8c86d5f9-bc9f-435c-ae33-cabf4b276640.png)

**Comment by ildar170975** [comment]
Why a user cannot reopen his own issues?
Imho an issue should be closed by a user who created it.

**Comment by htmltiger** [comment]
I have just tested it and workes fine, 
have you tried in incognito?

**Comment by htmltiger** [comment]
> Why a user cannot reopen his own issues? Imho an issue should be closed by a user who created it.

no idea how to setup this

**Comment by ildar170975** [comment]
> no idea how to setup this

OK, hope we'll manage it anyway ))).



> have you tried in incognito?

Strange.
I cleared a cache just in case, same in Chrome.
FF - checked too (cannot clear a cache here), same picture:
![image](https://user-images.githubusercontent.com/71872483/187754943-7240985b-d249-4efe-938c-7f4e942ad513.png)

Incognito in Chrome:
![image](https://user-images.githubusercontent.com/71872483/187755556-e57da7d4-c2e2-4e88-98ce-66b7322dddb6.png)

**Comment by htmltiger** [comment]
what are the state attributes in Home assistant > developer tools for `input_number.test_number_with_picture`

**Comment by ildar170975** [comment]
![image](https://user-images.githubusercontent.com/71872483/187757481-13ac5cfa-e7ef-4565-9a32-e2be41166037.png)

```
input_number:
  test_number_with_picture:
    min: -100
    max: 100
    step: 0.1
    mode: box

homeassistant:
  customize:
    input_number.test_number_with_picture:
      entity_picture: /local/images/test/lightgreen.jpg
```

**Comment by htmltiger** [comment]
works here with 3.16
![1](https://user-images.githubusercontent.com/1429451/187761464-9569ed86-ad95-4f96-927e-531fc743e6ce.png)
![2](https://user-images.githubusercontent.com/1429451/187761465-12c093a0-872f-45b3-a6c0-8b2f95954d5a.png)

**Comment by ildar170975** [comment]
Really strange.
Hope we are using same revision of numberbox.

Also - about your entity.
I noticed you are using `number.xxxx`, and I am using `input_number.xxxx`.
AFAIK `number` entities may be created by integrations only.
Just to be sure - could you test with a conventional `input_number`?

--------------

Found a reason.
Check this card:
```
type: entities
title: entity_picture
entities:
  - entity: input_number.test_number_with_picture
  - type: custom:numberbox-card
    entity: input_number.test_number_with_picture
  - type: custom:numberbox-card
    entity: input_number.test_number_with_picture
    icon: false
  - type: custom:numberbox-card
    entity: input_number.test_number_with_picture
    icon: mdi:car

  - type: section

  - entity: input_number.test_number_with_picture_icon
  - type: custom:numberbox-card
    entity: input_number.test_number_with_picture_icon
  - type: custom:numberbox-card
    entity: input_number.test_number_with_picture_icon
    icon: false
  - type: custom:numberbox-card
    entity: input_number.test_number_with_picture_icon
    icon: mdi:car
```
with these helpers:
```
input_number:
  test_number_with_picture:
    min: -100
    max: 100
    step: 0.1
    mode: box
  test_number_with_picture_icon:
    min: -100
    max: 100
    step: 0.1
    mode: box
    icon: mdi:account

homeassistant:
  customize:
    input_number.test_number_with_picture:
      entity_picture: /local/images/test/lightgreen.jpg
    input_number.test_number_with_picture_icon:
      entity_picture: /local/images/test/orange.jpg
```
The 2nd helper has `icon` property - which forces the image to be displayed - which is not supposed to cause this.
![image](https://user-images.githubusercontent.com/71872483/187779828-678f2534-4552-4435-83f6-1679caf769ea.png)
