### ISSUE TITLE
Toggle Switch

### ISSUE THREAD

**Issue by nochlab1** [htmltiger/numberbox-card#72]
Hi is it possible to add a option to have a toggle on the switch so i can control the temp on turn it n and off
Thanks

**Comment by mathieu-mp** [comment]
Hi,
Such a great work, I use it for months now... It should be core !!!
I would love to have a toggle button too, or how can we achieve that ?

**Comment by htmltiger** [comment]
It is possible to create with a switch when you use `type: horizontal-stack`

![130059 Overview – Home Assistant](https://user-images.githubusercontent.com/1429451/221186360-79674cd6-69a4-471f-8eea-5876d7152118.png)

```yaml
type: vertical-stack
title: Downstairs Heating
cards:
  - type: horizontal-stack
    cards:
      - type: custom:bignumber-card
        title: Current Temp
        entity: sensor.downstairs_c_temp
        info: sensor.downstairs_temp
        scale: 25px
        unit: ''
      - type: horizontal-stack
        cards:
          - type: button
            tap_action:
              action: more-info
            entity: sensor.downstairs_timerui
            show_name: false
            show_state: true
            show_icon: true
            icon: mdi:timelapse
            icon_height: 32px
            style: |
              :host { --paper-item-icon-color:#ccc; }
          - type: button
            tap_action:
              action: more-info
            entity: binary_sensor.downstairs_flame
            show_name: true
            show_state: false
            icon_height: 32px
            name: Status
            hold_action:
              action: none
            style: >
              ha-card {font-size:0.8rem !important;} :host {
              --paper-item-icon-active-color:#c00; --paper-item-icon-color:#ccc;
               }
          - type: button
            tap_action:
              action: toggle
            entity: switch.heat_auto_downstairs
            show_name: true
            icon_height: 32px
            name: Auto
            style: |
              ha-card {font-size:0.8rem !important;}
  - type: horizontal-stack
    cards:
      - type: entities
        entities:
          - type: custom:numberbox-card
            entity: climate.downstairs_heating
            name: false
            border: false
            initial: 0
            icon: false
            state: temperature
            service: set_temperature
            param: temperature
            min: 0
            max: 50
            step: 0.5
            style: >
              .grid{display:block!important} .grid-left{padding:0 !important;text-align:center!important}
               h3{font-size:40px !important}
              .body{display:block!important}
              .body::after{text-align:center;font-size:12px;content:"Set Temperature";display:block!important}
      - type: entities
        entities:
          - type: custom:numberbox-card
            entity: number.down_timer
            name: false
            border: false
            initial: 0
            icon: false
            style: >
              .grid{display:block!important} .grid-left{padding:0 !important;text-align:center!important}
               h3{font-size:40px !important}
              .body{display:block!important}
              .body::after{text-align:center;font-size:12px;content:"Timer";display:block!important}
        style: >
          .card-header{display:block!important;line-height:var(--ha-card-header-font-size, 35px) !important}
  - type: entities
    entities:
      - entity: sensor.downstairs_on_today
        name: Heat On Today
        icon: mdi:chart-line
    style: |
      .card-content{padding:0 16px !important}
  - type: horizontal-stack
    cards:
      - type: custom:apexcharts-card
        ...

```
