### ISSUE TITLE
With "min" & "max" defined: a glitch with changing a value

### ISSUE THREAD

**Issue by ildar170975** [htmltiger/numberbox-card#79]
Consider this example:
```
type: entities
entities:
  - input_number.test_number
  - type: custom:numberbox-card
    entity: input_number.test_number
    min: 10
    max: 20
title: min/max
```
The entity is a simple `input_number` entity, it does not have attributes `min`, `max`, `set`.
The code above gives this a strange behaviour when a user changes a value:

![n1](https://user-images.githubusercontent.com/71872483/221436078-0bab56b3-3c1e-4326-988e-adbd861189fa.gif)
