### ISSUE TITLE
is it possible to round a number in the secondary_info field?

### ISSUE THREAD

**Issue by valantur** [htmltiger/numberbox-card#94]
This isn't really a bug but a question:
I have a sensor with a value of "xx.xxxxxxx" and I would like to display it in the secondary_information field but rounded to two decimals.

`'Now: %sensor.thermostat_current_away_temp:state °F'` shows `Now: 71.388377 °F` and I would like it to show `Now: 71.39°F`

I know there are other ways to achieve this (like creating a template sensor and rounding that one) but I wonder if there  is a way to do it via HTML or whatever else, directly from the numberbox card.

Thanks!

**Comment by ildar170975** [comment]
I am also interested in this. 
The card seems to use neither jinjia nor js for addressing entities, so corresponding operations seem to be not available here.

**Comment by pos-ei-don** [comment]
Great Feature, but does not seem to work on states? Could only get it working on attributes.

**Comment by ildar170975** [comment]
Cannot get it working too:
![изображение](https://github.com/htmltiger/numberbox-card/assets/71872483/0d185904-fe2b-4061-bb48-7757ec632c0e)
```
type: entities
entities:
  - input_number.test_negative_11
  - type: custom:numberbox-card
    entity: input_number.test_negative_11
    name: html
    secondary_info: >-
      %input_number.test_negative_11:state:~1
```
![изображение](https://github.com/htmltiger/numberbox-card/assets/71872483/181ecf41-52f3-48f1-9a01-68b8a6b91f89)
